name: Unit tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Run Go Tests
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repositiry
        uses: actions/checkout@vmain
      - name: Set up Go
        uses: actions/setup-go@main
        with:
          go-version: "1.22"
      - name: Get dependecies
        run: go mod download
      - name: Run tests
        run: go test ./...
      - name: Display go version
        run: go version
