name: Build, Test and Publish

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22"

      - name: Get dependencies
        run: go mod download

      - name: Run tests
        run: go test ./...

      - name: Display Go version
        run: go version

  build-and-publish:
    name: Build and Publish Docker Image
    needs: test # This job needs the test job to succeed
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t leshax/webuyxchamd64:${{ github.sha }} .

      - name: Log in to Docker Hub
        uses: docker/login-action@v3.1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push Docker image to Docker Hub
        run: docker push leshax/webuyxchamd64:${{ github.sha }}
